name: Java CI with Maven

on:
  push:
    branches:
      - dev
      - '**'
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run Tests
        run: mvn clean test

      - name: Verify Dependencies and Compile
        run: mvn clean verify

      - name: Assign Reviewers
        if: github.event_name == 'pull_request'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "mpbialoszewski,KhurrumA,spartamq, younisrajaApplications,  mercy-njeru"
